### ISSUE TITLE
Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 

### ISSUE THREAD

**Issue by ghost** [dariopellegrini/StorageDone-iOS#1]
It has a compile error with Swift 5.1 for CouchbaseLiteSwift.

**Comment by dariopellegrini** [comment]
I'll check on Xcode 11 and let you know. Thanks for your feedback.

**Comment by ghost** [comment]
@dariopellegrini Cheers mate. Keep me updated pls.

**Comment by dariopellegrini** [comment]
@gabor-majorszki as you mentioned before, Couchbase needs to be recompiled with new Swift 5.1.
Couchbase iOS team is working on it as mentioned [here](https://github.com/couchbase/couchbase-lite-ios/issues/2546).

I'll make a new release as soon as the next Couchbase release will be available.
I'm keeping this issue open til then.

Thank you.

**Comment by meifu1709** [comment]
If this problem is solved, please let me know. I have the same problem.

**Comment by dariopellegrini** [comment]
Couchbase iOS team is still working on that.
While waiting can you try this version with the CouchbaseLiteSwift framework built by me?

`pod 'StorageDone', :git => 'https://github.com/dariopellegrini/StorageDone-iOS.git', :branch => 'swift5.1'`

Thank you.

**Comment by ghost** [comment]
@dariopellegrini I tried and it's working well now, but still got this warning message:
CouchbaseLite Database WARNING: Database.log.file.config is nil, meaning file logging is disabled. Log files required for product support are not being generated.
I don't think it's an issue, since it's just loggin, but might be interesting for you.

Thanks man. :)

**Comment by dariopellegrini** [comment]
@gabor-majorszki glad it works well. Keeping open this issue til all will be managed through Cocoapods.
For the logging issue thank you. As you said it shouldn't be an issue. Only a best practice warning probably. However I'll check how to remove it.

**Comment by dariopellegrini** [comment]
Ok all done in [0.8](https://github.com/dariopellegrini/StorageDone-iOS/releases/tag/0.8).

Thank you.
