### ISSUE TITLE
insertOrUpdate method is not updating DB

### ISSUE THREAD

**Issue by TOrnelas** [dariopellegrini/StorageDone-iOS#2]
I have implemented my User class  with the primaryKey() function:

```
struct User: Codable {
    var username: String
    var authToken: String
    
    func primaryKey() -> String {
        return "username"
    }
}
```

However, when I use the insertOrUpdate method, the user it's inserted again on the DB leaving me with duplicated user entries (with the same username)

**Comment by dariopellegrini** [comment]
Hello @TOrnelas.
You probably forgot to implement PrimaryKey protocol on that struct.

```swift
struct User: Codable, PrimaryKey {
    var username: String
    var authToken: String
    
    func primaryKey() -> String {
        return "username"
    }
}
```

You can find a reference here [https://github.com/dariopellegrini/StorageDone-iOS#primary-key](https://github.com/dariopellegrini/StorageDone-iOS#primary-key).

Let me know if your problem is solved.

**Comment by TOrnelas** [comment]
That was it! Thank you very much. Closing the issue
