### ISSUE TITLE
Auto increment id

### ISSUE THREAD

**Issue by BossJC69** [dariopellegrini/StorageDone-iOS#3]
Hello. Is there a way to have id auto increment?
Thank you.

**Comment by dariopellegrini** [comment]
Hello @BossJC69 ,
thanks for reaching out!
We are on a documental database, not a relational one.
Can I suggest, instead of auto increment id, to use a UUID?
Create one before insert the object.

```swift
UUID().uuidString
```

Can it be useful for you?

Thank you.

**Comment by BossJC69** [comment]
Yes it helped. Thank you
