### ISSUE TITLE
Truncate table

### ISSUE THREAD

**Issue by emirbeytekin** [dariopellegrini/StorageDone-iOS#5]
How can i truncate my table? I didn't see any solution

**Comment by dariopellegrini** [comment]
Hello @emirbeytekin . There are no tables here, just documents.
If you mean delete every document of a certain model you can use the delete function.
Here's an example with a model
```swift
struct Teacher {
   let id: String
   let name: String
   let surname: String
}
```

Use delete to delete every document of this model
```swift
try database.delete(Teacher.self)
```

Hope this helps.

**Comment by emirbeytekin** [comment]
thank u for response :) that's work it
